[tox]
requires =
    tox>=4
env_list =
    anki-current
    anki-earliest
    anki-beta
skipsdist = True

[testenv]
description = run unit tests
passenv = *
setenv =
    QT_QPA_PLATFORM = offscreen
commands =
    pytest -v --cov=cross_field_highlighter --cov-report=xml --cov-config=tox.ini --cov-branch

[testenv:anki-current]
deps =
    -r requirements/tests.txt
    -r requirements/anki-current.txt
commands =
    {[testenv]commands} {posargs:tests -m "not integration and not skip_for_current"}

[testenv:anki-earliest]
deps =
    -r requirements/tests.txt
    -r requirements/anki-earliest.txt
commands =
    {[testenv]commands} {posargs:tests -m "not integration and not skip_for_earliest"}

[testenv:anki-beta]
deps =
    -r requirements/tests.txt
    -r requirements/anki-beta.txt
commands =
    {[testenv]commands} {posargs:tests -m "not integration and not skip_for_beta"}
